# Generated by Django 4.2.7 on 2024-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fire_dectection_web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="Email_tram",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="information",
            name="Pass_Email_tram",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
