# Generated by Django 4.2.7 on 2024-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fire_dectection_web_app",
            "0002_information_email_tram_information_pass_email_tram",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Email_Tram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email_tram", models.CharField(default="", max_length=50, null=True)),
                (
                    "Pass_Email_tram",
                    models.CharField(default="", max_length=50, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="information",
            name="Email_tram",
        ),
        migrations.RemoveField(
            model_name="information",
            name="Pass_Email_tram",
        ),
    ]
