# Generated by Django 4.2.7 on 2024-01-17 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fire_dectection_web_app",
            "0003_email_tram_remove_information_email_tram_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Email_Tram",
            new_name="EmailTram",
        ),
    ]
