# Generated by Django 4.2.7 on 2024-01-17 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fire_dectection_web_app", "0004_rename_email_tram_emailtram"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTram",
        ),
    ]
