# Generated by Django 4.2.7 on 2024-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fire_dectection_web_app", "0005_delete_emailtram"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email_tram", models.CharField(default="", max_length=50, null=True)),
                (
                    "Pass_Email_tram",
                    models.CharField(default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
