# Generated by Django 4.2.7 on 2024-01-24 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fire_dectection_web_app", "0006_emailtram"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTram",
        ),
    ]
